//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.cybox_2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The ActionArgumentsType enables the specification of relevant arguments/parameters for this Action.
 * 
 * <p>Java class for ActionArgumentsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionArgumentsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action_Argument" type="{http://cybox.mitre.org/cybox-2}ActionArgumentType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionArgumentsType", propOrder = {
    "actionArguments"
})
public class ActionArgumentsType {

    @XmlElement(name = "Action_Argument", required = true)
    protected List<ActionArgumentType> actionArguments;

    /**
     * Gets the value of the actionArguments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionArguments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionArguments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionArgumentType }
     * 
     * 
     */
    public List<ActionArgumentType> getActionArguments() {
        if (actionArguments == null) {
            actionArguments = new ArrayList<ActionArgumentType>();
        }
        return this.actionArguments;
    }

}
