//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.stix.courseofaction_1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mitre.stix.courseofaction_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mitre.stix.courseofaction_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CourseOfAction }
     * 
     */
    public CourseOfAction createCourseOfAction() {
        return new CourseOfAction();
    }

    /**
     * Create an instance of {@link ObjectiveType }
     * 
     */
    public ObjectiveType createObjectiveType() {
        return new ObjectiveType();
    }

    /**
     * Create an instance of {@link RelatedCOAsType }
     * 
     */
    public RelatedCOAsType createRelatedCOAsType() {
        return new RelatedCOAsType();
    }

}
