//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CodeTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Source_Code"/>
 *     &lt;enumeration value="Byte_Code"/>
 *     &lt;enumeration value="Binary_Code"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CodeTypeEnum", namespace = "http://cybox.mitre.org/objects#CodeObject-2")
@XmlEnum
public enum CodeTypeEnum {


    /**
     * The code represented is in the form of Source Code.
     * 
     */
    @XmlEnumValue("Source_Code")
    SOURCE_CODE("Source_Code"),

    /**
     * The code represented is in the form of Byte Code.
     * 
     */
    @XmlEnumValue("Byte_Code")
    BYTE_CODE("Byte_Code"),

    /**
     * The code represented is in the form of binary code.
     * 
     */
    @XmlEnumValue("Binary_Code")
    BINARY_CODE("Binary_Code");
    private final String value;

    CodeTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CodeTypeEnum fromValue(String v) {
        for (CodeTypeEnum c: CodeTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
