//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DomainNameTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DomainNameTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FQDN"/>
 *     &lt;enumeration value="TLD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DomainNameTypeEnum", namespace = "http://cybox.mitre.org/objects#DomainNameObject-1")
@XmlEnum
public enum DomainNameTypeEnum {


    /**
     * Specifies a fully qualified domain name (FQDN), e.g. "www.abcd.com".
     * 
     */
    FQDN,

    /**
     * Specifies a top-level domain (TLD) name, e.g. ".com" or ".org".
     * 
     */
    TLD;

    public String value() {
        return name();
    }

    public static DomainNameTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
