//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.ObjectPropertiesType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The HostnameObjectType object is intended to specify network hostnames.
 * 
 * <p>Java class for HostnameObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HostnameObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/common-2}ObjectPropertiesType">
 *       &lt;sequence>
 *         &lt;element name="Hostname_Value" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Naming_System" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="is_domain_name" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostnameObjectType", namespace = "http://cybox.mitre.org/objects#HostnameObject-1", propOrder = {
    "hostnameValue",
    "namingSystems"
})
@XmlRootElement(name = "Hostname", namespace = "http://cybox.mitre.org/objects#HostnameObject-1")
public class Hostname
    extends ObjectPropertiesType
{

    @XmlElement(name = "Hostname_Value")
    protected StringObjectPropertyType hostnameValue;
    @XmlElement(name = "Naming_System")
    protected List<StringObjectPropertyType> namingSystems;
    @XmlAttribute(name = "is_domain_name")
    protected Boolean isDomainName;

    /**
     * Gets the value of the hostnameValue property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getHostnameValue() {
        return hostnameValue;
    }

    /**
     * Sets the value of the hostnameValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setHostnameValue(StringObjectPropertyType value) {
        this.hostnameValue = value;
    }

    /**
     * Gets the value of the namingSystems property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namingSystems property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamingSystems().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringObjectPropertyType }
     * 
     * 
     */
    public List<StringObjectPropertyType> getNamingSystems() {
        if (namingSystems == null) {
            namingSystems = new ArrayList<StringObjectPropertyType>();
        }
        return this.namingSystems;
    }

    /**
     * Gets the value of the isDomainName property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDomainName() {
        return isDomainName;
    }

    /**
     * Sets the value of the isDomainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDomainName(Boolean value) {
        this.isDomainName = value;
    }

}
