//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IANAEtherTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IANAEtherTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IPv4(0x0800)"/>
 *     &lt;enumeration value="ARP(0x0806)"/>
 *     &lt;enumeration value="RARP(0x8035)"/>
 *     &lt;enumeration value="IPX(0x8137)"/>
 *     &lt;enumeration value="SNMP(0x814C)"/>
 *     &lt;enumeration value="IPv6(0x86DD)"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IANAEtherTypeEnum")
@XmlEnum
public enum IANAEtherTypeEnum {


    /**
     * Indicates the IPv4 Ethernet type is specified.
     * 
     */
    @XmlEnumValue("IPv4(0x0800)")
    I_PV_4_0_X_0800("IPv4(0x0800)"),

    /**
     * Indicates the ARP Ethernet type is specified.
     * 
     */
    @XmlEnumValue("ARP(0x0806)")
    ARP_0_X_0806("ARP(0x0806)"),

    /**
     * Indicates the RARP Ethernet type is specified.
     * 
     */
    @XmlEnumValue("RARP(0x8035)")
    RARP_0_X_8035("RARP(0x8035)"),

    /**
     * Indicates the IPX Ethernet type is specified.
     * 
     */
    @XmlEnumValue("IPX(0x8137)")
    IPX_0_X_8137("IPX(0x8137)"),

    /**
     * Indicates the SNMP Ethernet type is specified.
     * 
     */
    @XmlEnumValue("SNMP(0x814C)")
    SNMP_0_X_814_C("SNMP(0x814C)"),

    /**
     * Indicates the IPv6 Ethernet type is specified.
     * 
     */
    @XmlEnumValue("IPv6(0x86DD)")
    I_PV_6_0_X_86_DD("IPv6(0x86DD)");
    private final String value;

    IANAEtherTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IANAEtherTypeEnum fromValue(String v) {
        for (IANAEtherTypeEnum c: IANAEtherTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
