//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.IntegerObjectPropertyType;
import org.mitre.cybox.common_2.PositiveIntegerObjectPropertyType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The ImageFileObjectType type is intended to characterize image files.
 * 
 * <p>Java class for ImageFileObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageFileObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/objects#FileObject-2}FileObjectType">
 *       &lt;sequence>
 *         &lt;element name="Image_File_Format" type="{http://cybox.mitre.org/objects#ImageFileObject-1}ImageFileFormatType" minOccurs="0"/>
 *         &lt;element name="Image_Height" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Image_Width" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Bits_Per_Pixel" type="{http://cybox.mitre.org/common-2}PositiveIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Compression_Algorithm" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="image_is_compressed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageFileObjectType", namespace = "http://cybox.mitre.org/objects#ImageFileObject-1", propOrder = {
    "imageFileFormat",
    "imageHeight",
    "imageWidth",
    "bitsPerPixel",
    "compressionAlgorithm"
})
@XmlRootElement(name = "Image_File", namespace = "http://cybox.mitre.org/objects#ImageFileObject-1")
public class ImageFile
    extends FileObjectType
{

    @XmlElement(name = "Image_File_Format")
    protected ImageFileFormatType imageFileFormat;
    @XmlElement(name = "Image_Height")
    protected IntegerObjectPropertyType imageHeight;
    @XmlElement(name = "Image_Width")
    protected IntegerObjectPropertyType imageWidth;
    @XmlElement(name = "Bits_Per_Pixel")
    protected PositiveIntegerObjectPropertyType bitsPerPixel;
    @XmlElement(name = "Compression_Algorithm")
    protected StringObjectPropertyType compressionAlgorithm;
    @XmlAttribute(name = "image_is_compressed")
    protected Boolean imageIsCompressed;

    /**
     * Gets the value of the imageFileFormat property.
     * 
     * @return
     *     possible object is
     *     {@link ImageFileFormatType }
     *     
     */
    public ImageFileFormatType getImageFileFormat() {
        return imageFileFormat;
    }

    /**
     * Sets the value of the imageFileFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageFileFormatType }
     *     
     */
    public void setImageFileFormat(ImageFileFormatType value) {
        this.imageFileFormat = value;
    }

    /**
     * Gets the value of the imageHeight property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public IntegerObjectPropertyType getImageHeight() {
        return imageHeight;
    }

    /**
     * Sets the value of the imageHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public void setImageHeight(IntegerObjectPropertyType value) {
        this.imageHeight = value;
    }

    /**
     * Gets the value of the imageWidth property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public IntegerObjectPropertyType getImageWidth() {
        return imageWidth;
    }

    /**
     * Sets the value of the imageWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public void setImageWidth(IntegerObjectPropertyType value) {
        this.imageWidth = value;
    }

    /**
     * Gets the value of the bitsPerPixel property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveIntegerObjectPropertyType }
     *     
     */
    public PositiveIntegerObjectPropertyType getBitsPerPixel() {
        return bitsPerPixel;
    }

    /**
     * Sets the value of the bitsPerPixel property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveIntegerObjectPropertyType }
     *     
     */
    public void setBitsPerPixel(PositiveIntegerObjectPropertyType value) {
        this.bitsPerPixel = value;
    }

    /**
     * Gets the value of the compressionAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getCompressionAlgorithm() {
        return compressionAlgorithm;
    }

    /**
     * Sets the value of the compressionAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setCompressionAlgorithm(StringObjectPropertyType value) {
        this.compressionAlgorithm = value;
    }

    /**
     * Gets the value of the imageIsCompressed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isImageIsCompressed() {
        return imageIsCompressed;
    }

    /**
     * Sets the value of the imageIsCompressed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setImageIsCompressed(Boolean value) {
        this.imageIsCompressed = value;
    }

}
