//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The IShowMessageActionType type characterizes IShowMessage actions.
 * 
 * <p>Java class for IShowMessageActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IShowMessageActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Show_Message_Body" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Show_Message_Title" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IShowMessageActionType", namespace = "http://cybox.mitre.org/objects#WinTaskObject-2", propOrder = {
    "showMessageBody",
    "showMessageTitle"
})
public class IShowMessageActionType {

    @XmlElement(name = "Show_Message_Body")
    protected StringObjectPropertyType showMessageBody;
    @XmlElement(name = "Show_Message_Title")
    protected StringObjectPropertyType showMessageTitle;

    /**
     * Gets the value of the showMessageBody property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getShowMessageBody() {
        return showMessageBody;
    }

    /**
     * Sets the value of the showMessageBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setShowMessageBody(StringObjectPropertyType value) {
        this.showMessageBody = value;
    }

    /**
     * Gets the value of the showMessageTitle property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getShowMessageTitle() {
        return showMessageTitle;
    }

    /**
     * Sets the value of the showMessageTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setShowMessageTitle(StringObjectPropertyType value) {
        this.showMessageTitle = value;
    }

}
