//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.ExtractedFeaturesType;
import org.mitre.cybox.common_2.HexBinaryObjectPropertyType;
import org.mitre.cybox.common_2.ObjectPropertiesType;
import org.mitre.cybox.common_2.StringObjectPropertyType;
import org.mitre.cybox.common_2.UnsignedLongObjectPropertyType;


/**
 * The LibraryObjectType type is intended to characterize software libraries.
 * 
 * <p>Java class for LibraryObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LibraryObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/common-2}ObjectPropertiesType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Path" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Size" type="{http://cybox.mitre.org/common-2}UnsignedLongObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://cybox.mitre.org/objects#LibraryObject-2}LibraryType" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Base_Address" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Extracted_Features" type="{http://cybox.mitre.org/common-2}ExtractedFeaturesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LibraryObjectType", namespace = "http://cybox.mitre.org/objects#LibraryObject-2", propOrder = {
    "name",
    "path",
    "size",
    "type",
    "version",
    "baseAddress",
    "extractedFeatures"
})
@XmlRootElement(name = "Library", namespace = "http://cybox.mitre.org/objects#LibraryObject-2")
public class Library
    extends ObjectPropertiesType
{

    @XmlElement(name = "Name")
    protected StringObjectPropertyType name;
    @XmlElement(name = "Path")
    protected StringObjectPropertyType path;
    @XmlElement(name = "Size")
    protected UnsignedLongObjectPropertyType size;
    @XmlElement(name = "Type")
    protected LibraryType type;
    @XmlElement(name = "Version")
    protected StringObjectPropertyType version;
    @XmlElement(name = "Base_Address")
    protected HexBinaryObjectPropertyType baseAddress;
    @XmlElement(name = "Extracted_Features")
    protected ExtractedFeaturesType extractedFeatures;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setName(StringObjectPropertyType value) {
        this.name = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setPath(StringObjectPropertyType value) {
        this.path = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedLongObjectPropertyType }
     *     
     */
    public UnsignedLongObjectPropertyType getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedLongObjectPropertyType }
     *     
     */
    public void setSize(UnsignedLongObjectPropertyType value) {
        this.size = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link LibraryType }
     *     
     */
    public LibraryType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link LibraryType }
     *     
     */
    public void setType(LibraryType value) {
        this.type = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setVersion(StringObjectPropertyType value) {
        this.version = value;
    }

    /**
     * Gets the value of the baseAddress property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getBaseAddress() {
        return baseAddress;
    }

    /**
     * Sets the value of the baseAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setBaseAddress(HexBinaryObjectPropertyType value) {
        this.baseAddress = value;
    }

    /**
     * Gets the value of the extractedFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link ExtractedFeaturesType }
     *     
     */
    public ExtractedFeaturesType getExtractedFeatures() {
        return extractedFeatures;
    }

    /**
     * Sets the value of the extractedFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtractedFeaturesType }
     *     
     */
    public void setExtractedFeatures(ExtractedFeaturesType value) {
        this.extractedFeatures = value;
    }

}
