//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.NonNegativeIntegerObjectPropertyType;
import org.mitre.cybox.common_2.ObjectPropertiesType;


/**
 * The NetworkSocketObjectType is intended to characterize network sockets.
 * 
 * <p>Java class for NetworkSocketObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkSocketObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/common-2}ObjectPropertiesType">
 *       &lt;sequence>
 *         &lt;element name="Address_Family" type="{http://cybox.mitre.org/objects#NetworkSocketObject-2}AddressFamilyType" minOccurs="0"/>
 *         &lt;element name="Domain" type="{http://cybox.mitre.org/objects#NetworkSocketObject-2}DomainFamilyType" minOccurs="0"/>
 *         &lt;element name="Local_Address" type="{http://cybox.mitre.org/objects#SocketAddressObject-1}SocketAddressObjectType" minOccurs="0"/>
 *         &lt;element name="Options" type="{http://cybox.mitre.org/objects#NetworkSocketObject-2}SocketOptionsType" minOccurs="0"/>
 *         &lt;element name="Protocol" type="{http://cybox.mitre.org/objects#NetworkSocketObject-2}ProtocolType" minOccurs="0"/>
 *         &lt;element name="Remote_Address" type="{http://cybox.mitre.org/objects#SocketAddressObject-1}SocketAddressObjectType" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://cybox.mitre.org/objects#NetworkSocketObject-2}SocketType" minOccurs="0"/>
 *         &lt;element name="Socket_Descriptor" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="is_blocking" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="is_listening" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkSocketObjectType", namespace = "http://cybox.mitre.org/objects#NetworkSocketObject-2", propOrder = {
    "addressFamily",
    "domain",
    "localAddress",
    "options",
    "protocol",
    "remoteAddress",
    "type",
    "socketDescriptor"
})
@XmlRootElement(name = "Network_Socket", namespace = "http://cybox.mitre.org/objects#NetworkSocketObject-2")
public class NetworkSocket
    extends ObjectPropertiesType
{

    @XmlElement(name = "Address_Family")
    protected AddressFamilyType addressFamily;
    @XmlElement(name = "Domain")
    protected DomainFamilyType domain;
    @XmlElement(name = "Local_Address")
    protected SocketAddress localAddress;
    @XmlElement(name = "Options")
    protected SocketOptionsType options;
    @XmlElement(name = "Protocol")
    protected ProtocolType protocol;
    @XmlElement(name = "Remote_Address")
    protected SocketAddress remoteAddress;
    @XmlElement(name = "Type")
    protected SocketType type;
    @XmlElement(name = "Socket_Descriptor")
    protected NonNegativeIntegerObjectPropertyType socketDescriptor;
    @XmlAttribute(name = "is_blocking")
    protected Boolean isBlocking;
    @XmlAttribute(name = "is_listening")
    protected Boolean isListening;

    /**
     * Gets the value of the addressFamily property.
     * 
     * @return
     *     possible object is
     *     {@link AddressFamilyType }
     *     
     */
    public AddressFamilyType getAddressFamily() {
        return addressFamily;
    }

    /**
     * Sets the value of the addressFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressFamilyType }
     *     
     */
    public void setAddressFamily(AddressFamilyType value) {
        this.addressFamily = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link DomainFamilyType }
     *     
     */
    public DomainFamilyType getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainFamilyType }
     *     
     */
    public void setDomain(DomainFamilyType value) {
        this.domain = value;
    }

    /**
     * Gets the value of the localAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SocketAddress }
     *     
     */
    public SocketAddress getLocalAddress() {
        return localAddress;
    }

    /**
     * Sets the value of the localAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocketAddress }
     *     
     */
    public void setLocalAddress(SocketAddress value) {
        this.localAddress = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link SocketOptionsType }
     *     
     */
    public SocketOptionsType getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocketOptionsType }
     *     
     */
    public void setOptions(SocketOptionsType value) {
        this.options = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolType }
     *     
     */
    public ProtocolType getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolType }
     *     
     */
    public void setProtocol(ProtocolType value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the remoteAddress property.
     * 
     * @return
     *     possible object is
     *     {@link SocketAddress }
     *     
     */
    public SocketAddress getRemoteAddress() {
        return remoteAddress;
    }

    /**
     * Sets the value of the remoteAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocketAddress }
     *     
     */
    public void setRemoteAddress(SocketAddress value) {
        this.remoteAddress = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SocketType }
     *     
     */
    public SocketType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocketType }
     *     
     */
    public void setType(SocketType value) {
        this.type = value;
    }

    /**
     * Gets the value of the socketDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getSocketDescriptor() {
        return socketDescriptor;
    }

    /**
     * Sets the value of the socketDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setSocketDescriptor(NonNegativeIntegerObjectPropertyType value) {
        this.socketDescriptor = value;
    }

    /**
     * Gets the value of the isBlocking property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBlocking() {
        return isBlocking;
    }

    /**
     * Sets the value of the isBlocking property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBlocking(Boolean value) {
        this.isBlocking = value;
    }

    /**
     * Gets the value of the isListening property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsListening() {
        return isListening;
    }

    /**
     * Sets the value of the isListening property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsListening(Boolean value) {
        this.isListening = value;
    }

}
