//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.HashListType;
import org.mitre.cybox.common_2.HexBinaryObjectPropertyType;
import org.mitre.cybox.common_2.NonNegativeIntegerObjectPropertyType;


/**
 * The PEFileHeaderType type refers to the PE file header (sometimes referred to as the COFF header) and its associated characteristics.
 * 
 * <p>Java class for PEFileHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PEFileHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Machine" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Number_Of_Sections" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Time_Date_Stamp" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Pointer_To_Symbol_Table" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Number_Of_Symbols" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Size_Of_Optional_Header" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Characteristics" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Hashes" type="{http://cybox.mitre.org/common-2}HashListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PEFileHeaderType", namespace = "http://cybox.mitre.org/objects#WinExecutableFileObject-2", propOrder = {
    "machine",
    "numberOfSections",
    "timeDateStamp",
    "pointerToSymbolTable",
    "numberOfSymbols",
    "sizeOfOptionalHeader",
    "characteristics",
    "hashes"
})
public class PEFileHeaderType {

    @XmlElement(name = "Machine")
    protected HexBinaryObjectPropertyType machine;
    @XmlElement(name = "Number_Of_Sections")
    protected NonNegativeIntegerObjectPropertyType numberOfSections;
    @XmlElement(name = "Time_Date_Stamp")
    protected HexBinaryObjectPropertyType timeDateStamp;
    @XmlElement(name = "Pointer_To_Symbol_Table")
    protected HexBinaryObjectPropertyType pointerToSymbolTable;
    @XmlElement(name = "Number_Of_Symbols")
    protected NonNegativeIntegerObjectPropertyType numberOfSymbols;
    @XmlElement(name = "Size_Of_Optional_Header")
    protected HexBinaryObjectPropertyType sizeOfOptionalHeader;
    @XmlElement(name = "Characteristics")
    protected HexBinaryObjectPropertyType characteristics;
    @XmlElement(name = "Hashes")
    protected HashListType hashes;

    /**
     * Gets the value of the machine property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getMachine() {
        return machine;
    }

    /**
     * Sets the value of the machine property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setMachine(HexBinaryObjectPropertyType value) {
        this.machine = value;
    }

    /**
     * Gets the value of the numberOfSections property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getNumberOfSections() {
        return numberOfSections;
    }

    /**
     * Sets the value of the numberOfSections property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setNumberOfSections(NonNegativeIntegerObjectPropertyType value) {
        this.numberOfSections = value;
    }

    /**
     * Gets the value of the timeDateStamp property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getTimeDateStamp() {
        return timeDateStamp;
    }

    /**
     * Sets the value of the timeDateStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setTimeDateStamp(HexBinaryObjectPropertyType value) {
        this.timeDateStamp = value;
    }

    /**
     * Gets the value of the pointerToSymbolTable property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getPointerToSymbolTable() {
        return pointerToSymbolTable;
    }

    /**
     * Sets the value of the pointerToSymbolTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setPointerToSymbolTable(HexBinaryObjectPropertyType value) {
        this.pointerToSymbolTable = value;
    }

    /**
     * Gets the value of the numberOfSymbols property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getNumberOfSymbols() {
        return numberOfSymbols;
    }

    /**
     * Sets the value of the numberOfSymbols property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setNumberOfSymbols(NonNegativeIntegerObjectPropertyType value) {
        this.numberOfSymbols = value;
    }

    /**
     * Gets the value of the sizeOfOptionalHeader property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getSizeOfOptionalHeader() {
        return sizeOfOptionalHeader;
    }

    /**
     * Sets the value of the sizeOfOptionalHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setSizeOfOptionalHeader(HexBinaryObjectPropertyType value) {
        this.sizeOfOptionalHeader = value;
    }

    /**
     * Gets the value of the characteristics property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getCharacteristics() {
        return characteristics;
    }

    /**
     * Sets the value of the characteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setCharacteristics(HexBinaryObjectPropertyType value) {
        this.characteristics = value;
    }

    /**
     * Gets the value of the hashes property.
     * 
     * @return
     *     possible object is
     *     {@link HashListType }
     *     
     */
    public HashListType getHashes() {
        return hashes;
    }

    /**
     * Sets the value of the hashes property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashListType }
     *     
     */
    public void setHashes(HashListType value) {
        this.hashes = value;
    }

}
