//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.HexBinaryObjectPropertyType;
import org.mitre.cybox.common_2.NonNegativeIntegerObjectPropertyType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The PESectionHeaderStruct type is intended as container for the properties relevant to a PE binary's section header structure.
 * 
 * <p>Java class for PESectionHeaderStructType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PESectionHeaderStructType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Virtual_Size" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Virtual_Address" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Size_Of_Raw_Data" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Pointer_To_Raw_Data" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Pointer_To_Relocations" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Pointer_To_Linenumbers" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Number_Of_Relocations" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Number_Of_Linenumbers" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Characteristics" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PESectionHeaderStructType", namespace = "http://cybox.mitre.org/objects#WinExecutableFileObject-2", propOrder = {
    "name",
    "virtualSize",
    "virtualAddress",
    "sizeOfRawData",
    "pointerToRawData",
    "pointerToRelocations",
    "pointerToLinenumbers",
    "numberOfRelocations",
    "numberOfLinenumbers",
    "characteristics"
})
public class PESectionHeaderStructType {

    @XmlElement(name = "Name")
    protected StringObjectPropertyType name;
    @XmlElement(name = "Virtual_Size")
    protected HexBinaryObjectPropertyType virtualSize;
    @XmlElement(name = "Virtual_Address")
    protected HexBinaryObjectPropertyType virtualAddress;
    @XmlElement(name = "Size_Of_Raw_Data")
    protected HexBinaryObjectPropertyType sizeOfRawData;
    @XmlElement(name = "Pointer_To_Raw_Data")
    protected HexBinaryObjectPropertyType pointerToRawData;
    @XmlElement(name = "Pointer_To_Relocations")
    protected HexBinaryObjectPropertyType pointerToRelocations;
    @XmlElement(name = "Pointer_To_Linenumbers")
    protected HexBinaryObjectPropertyType pointerToLinenumbers;
    @XmlElement(name = "Number_Of_Relocations")
    protected NonNegativeIntegerObjectPropertyType numberOfRelocations;
    @XmlElement(name = "Number_Of_Linenumbers")
    protected NonNegativeIntegerObjectPropertyType numberOfLinenumbers;
    @XmlElement(name = "Characteristics")
    protected HexBinaryObjectPropertyType characteristics;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setName(StringObjectPropertyType value) {
        this.name = value;
    }

    /**
     * Gets the value of the virtualSize property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getVirtualSize() {
        return virtualSize;
    }

    /**
     * Sets the value of the virtualSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setVirtualSize(HexBinaryObjectPropertyType value) {
        this.virtualSize = value;
    }

    /**
     * Gets the value of the virtualAddress property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getVirtualAddress() {
        return virtualAddress;
    }

    /**
     * Sets the value of the virtualAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setVirtualAddress(HexBinaryObjectPropertyType value) {
        this.virtualAddress = value;
    }

    /**
     * Gets the value of the sizeOfRawData property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getSizeOfRawData() {
        return sizeOfRawData;
    }

    /**
     * Sets the value of the sizeOfRawData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setSizeOfRawData(HexBinaryObjectPropertyType value) {
        this.sizeOfRawData = value;
    }

    /**
     * Gets the value of the pointerToRawData property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getPointerToRawData() {
        return pointerToRawData;
    }

    /**
     * Sets the value of the pointerToRawData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setPointerToRawData(HexBinaryObjectPropertyType value) {
        this.pointerToRawData = value;
    }

    /**
     * Gets the value of the pointerToRelocations property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getPointerToRelocations() {
        return pointerToRelocations;
    }

    /**
     * Sets the value of the pointerToRelocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setPointerToRelocations(HexBinaryObjectPropertyType value) {
        this.pointerToRelocations = value;
    }

    /**
     * Gets the value of the pointerToLinenumbers property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getPointerToLinenumbers() {
        return pointerToLinenumbers;
    }

    /**
     * Sets the value of the pointerToLinenumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setPointerToLinenumbers(HexBinaryObjectPropertyType value) {
        this.pointerToLinenumbers = value;
    }

    /**
     * Gets the value of the numberOfRelocations property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getNumberOfRelocations() {
        return numberOfRelocations;
    }

    /**
     * Sets the value of the numberOfRelocations property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setNumberOfRelocations(NonNegativeIntegerObjectPropertyType value) {
        this.numberOfRelocations = value;
    }

    /**
     * Gets the value of the numberOfLinenumbers property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getNumberOfLinenumbers() {
        return numberOfLinenumbers;
    }

    /**
     * Sets the value of the numberOfLinenumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setNumberOfLinenumbers(NonNegativeIntegerObjectPropertyType value) {
        this.numberOfLinenumbers = value;
    }

    /**
     * Gets the value of the characteristics property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getCharacteristics() {
        return characteristics;
    }

    /**
     * Sets the value of the characteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setCharacteristics(HexBinaryObjectPropertyType value) {
        this.characteristics = value;
    }

}
