//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.DateTimeObjectPropertyType;
import org.mitre.cybox.common_2.DurationObjectPropertyType;
import org.mitre.cybox.common_2.EnvironmentVariableListType;
import org.mitre.cybox.common_2.ExtractedFeaturesType;
import org.mitre.cybox.common_2.ObjectPropertiesType;
import org.mitre.cybox.common_2.StringObjectPropertyType;
import org.mitre.cybox.common_2.UnsignedIntegerObjectPropertyType;


/**
 * The ProcessObjectType type is intended to characterize system processes.
 * 
 * <p>Java class for ProcessObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/common-2}ObjectPropertiesType">
 *       &lt;sequence>
 *         &lt;element name="PID" type="{http://cybox.mitre.org/common-2}UnsignedIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Creation_Time" type="{http://cybox.mitre.org/common-2}DateTimeObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Parent_PID" type="{http://cybox.mitre.org/common-2}UnsignedIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Child_PID_List" type="{http://cybox.mitre.org/objects#ProcessObject-2}ChildPIDListType" minOccurs="0"/>
 *         &lt;element name="Image_Info" type="{http://cybox.mitre.org/objects#ProcessObject-2}ImageInfoType" minOccurs="0"/>
 *         &lt;element name="Argument_List" type="{http://cybox.mitre.org/objects#ProcessObject-2}ArgumentListType" minOccurs="0"/>
 *         &lt;element name="Environment_Variable_List" type="{http://cybox.mitre.org/common-2}EnvironmentVariableListType" minOccurs="0"/>
 *         &lt;element name="Kernel_Time" type="{http://cybox.mitre.org/common-2}DurationObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Port_List" type="{http://cybox.mitre.org/objects#ProcessObject-2}PortListType" minOccurs="0"/>
 *         &lt;element name="Network_Connection_List" type="{http://cybox.mitre.org/objects#ProcessObject-2}NetworkConnectionListType" minOccurs="0"/>
 *         &lt;element name="Start_Time" type="{http://cybox.mitre.org/common-2}DateTimeObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://cybox.mitre.org/objects#ProcessObject-2}ProcessStatusType" minOccurs="0"/>
 *         &lt;element name="Username" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="User_Time" type="{http://cybox.mitre.org/common-2}DurationObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Extracted_Features" type="{http://cybox.mitre.org/common-2}ExtractedFeaturesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="is_hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessObjectType", namespace = "http://cybox.mitre.org/objects#ProcessObject-2", propOrder = {
    "pid",
    "name",
    "creationTime",
    "parentPID",
    "childPIDList",
    "imageInfo",
    "argumentList",
    "environmentVariableList",
    "kernelTime",
    "portList",
    "networkConnectionList",
    "startTime",
    "status",
    "username",
    "userTime",
    "extractedFeatures"
})
@XmlSeeAlso({
    UnixProcess.class,
    WindowsProcessObjectType.class
})
public class ProcessObjectType
    extends ObjectPropertiesType
{

    @XmlElement(name = "PID")
    protected UnsignedIntegerObjectPropertyType pid;
    @XmlElement(name = "Name")
    protected StringObjectPropertyType name;
    @XmlElement(name = "Creation_Time")
    protected DateTimeObjectPropertyType creationTime;
    @XmlElement(name = "Parent_PID")
    protected UnsignedIntegerObjectPropertyType parentPID;
    @XmlElement(name = "Child_PID_List")
    protected ChildPIDListType childPIDList;
    @XmlElement(name = "Image_Info")
    protected ImageInfoType imageInfo;
    @XmlElement(name = "Argument_List")
    protected ArgumentListType argumentList;
    @XmlElement(name = "Environment_Variable_List")
    protected EnvironmentVariableListType environmentVariableList;
    @XmlElement(name = "Kernel_Time")
    protected DurationObjectPropertyType kernelTime;
    @XmlElement(name = "Port_List")
    protected PortListType portList;
    @XmlElement(name = "Network_Connection_List")
    protected NetworkConnectionListType networkConnectionList;
    @XmlElement(name = "Start_Time")
    protected DateTimeObjectPropertyType startTime;
    @XmlElement(name = "Status")
    protected ProcessStatusType status;
    @XmlElement(name = "Username")
    protected StringObjectPropertyType username;
    @XmlElement(name = "User_Time")
    protected DurationObjectPropertyType userTime;
    @XmlElement(name = "Extracted_Features")
    protected ExtractedFeaturesType extractedFeatures;
    @XmlAttribute(name = "is_hidden")
    protected Boolean isHidden;

    /**
     * Gets the value of the pid property.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedIntegerObjectPropertyType }
     *     
     */
    public UnsignedIntegerObjectPropertyType getPID() {
        return pid;
    }

    /**
     * Sets the value of the pid property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedIntegerObjectPropertyType }
     *     
     */
    public void setPID(UnsignedIntegerObjectPropertyType value) {
        this.pid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setName(StringObjectPropertyType value) {
        this.name = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeObjectPropertyType }
     *     
     */
    public DateTimeObjectPropertyType getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeObjectPropertyType }
     *     
     */
    public void setCreationTime(DateTimeObjectPropertyType value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the parentPID property.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedIntegerObjectPropertyType }
     *     
     */
    public UnsignedIntegerObjectPropertyType getParentPID() {
        return parentPID;
    }

    /**
     * Sets the value of the parentPID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedIntegerObjectPropertyType }
     *     
     */
    public void setParentPID(UnsignedIntegerObjectPropertyType value) {
        this.parentPID = value;
    }

    /**
     * Gets the value of the childPIDList property.
     * 
     * @return
     *     possible object is
     *     {@link ChildPIDListType }
     *     
     */
    public ChildPIDListType getChildPIDList() {
        return childPIDList;
    }

    /**
     * Sets the value of the childPIDList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildPIDListType }
     *     
     */
    public void setChildPIDList(ChildPIDListType value) {
        this.childPIDList = value;
    }

    /**
     * Gets the value of the imageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ImageInfoType }
     *     
     */
    public ImageInfoType getImageInfo() {
        return imageInfo;
    }

    /**
     * Sets the value of the imageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageInfoType }
     *     
     */
    public void setImageInfo(ImageInfoType value) {
        this.imageInfo = value;
    }

    /**
     * Gets the value of the argumentList property.
     * 
     * @return
     *     possible object is
     *     {@link ArgumentListType }
     *     
     */
    public ArgumentListType getArgumentList() {
        return argumentList;
    }

    /**
     * Sets the value of the argumentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArgumentListType }
     *     
     */
    public void setArgumentList(ArgumentListType value) {
        this.argumentList = value;
    }

    /**
     * Gets the value of the environmentVariableList property.
     * 
     * @return
     *     possible object is
     *     {@link EnvironmentVariableListType }
     *     
     */
    public EnvironmentVariableListType getEnvironmentVariableList() {
        return environmentVariableList;
    }

    /**
     * Sets the value of the environmentVariableList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnvironmentVariableListType }
     *     
     */
    public void setEnvironmentVariableList(EnvironmentVariableListType value) {
        this.environmentVariableList = value;
    }

    /**
     * Gets the value of the kernelTime property.
     * 
     * @return
     *     possible object is
     *     {@link DurationObjectPropertyType }
     *     
     */
    public DurationObjectPropertyType getKernelTime() {
        return kernelTime;
    }

    /**
     * Sets the value of the kernelTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationObjectPropertyType }
     *     
     */
    public void setKernelTime(DurationObjectPropertyType value) {
        this.kernelTime = value;
    }

    /**
     * Gets the value of the portList property.
     * 
     * @return
     *     possible object is
     *     {@link PortListType }
     *     
     */
    public PortListType getPortList() {
        return portList;
    }

    /**
     * Sets the value of the portList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortListType }
     *     
     */
    public void setPortList(PortListType value) {
        this.portList = value;
    }

    /**
     * Gets the value of the networkConnectionList property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkConnectionListType }
     *     
     */
    public NetworkConnectionListType getNetworkConnectionList() {
        return networkConnectionList;
    }

    /**
     * Sets the value of the networkConnectionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkConnectionListType }
     *     
     */
    public void setNetworkConnectionList(NetworkConnectionListType value) {
        this.networkConnectionList = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeObjectPropertyType }
     *     
     */
    public DateTimeObjectPropertyType getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeObjectPropertyType }
     *     
     */
    public void setStartTime(DateTimeObjectPropertyType value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessStatusType }
     *     
     */
    public ProcessStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessStatusType }
     *     
     */
    public void setStatus(ProcessStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setUsername(StringObjectPropertyType value) {
        this.username = value;
    }

    /**
     * Gets the value of the userTime property.
     * 
     * @return
     *     possible object is
     *     {@link DurationObjectPropertyType }
     *     
     */
    public DurationObjectPropertyType getUserTime() {
        return userTime;
    }

    /**
     * Sets the value of the userTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DurationObjectPropertyType }
     *     
     */
    public void setUserTime(DurationObjectPropertyType value) {
        this.userTime = value;
    }

    /**
     * Gets the value of the extractedFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link ExtractedFeaturesType }
     *     
     */
    public ExtractedFeaturesType getExtractedFeatures() {
        return extractedFeatures;
    }

    /**
     * Sets the value of the extractedFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtractedFeaturesType }
     *     
     */
    public void setExtractedFeatures(ExtractedFeaturesType value) {
        this.extractedFeatures = value;
    }

    /**
     * Gets the value of the isHidden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsHidden() {
        return isHidden;
    }

    /**
     * Sets the value of the isHidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsHidden(Boolean value) {
        this.isHidden = value;
    }

}
