//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessorArchEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProcessorArchEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="x86-32"/>
 *     &lt;enumeration value="x86-64"/>
 *     &lt;enumeration value="IA-64"/>
 *     &lt;enumeration value="PowerPC"/>
 *     &lt;enumeration value="ARM"/>
 *     &lt;enumeration value="Alpha"/>
 *     &lt;enumeration value="SPARC"/>
 *     &lt;enumeration value="z/Architecture"/>
 *     &lt;enumeration value="eSi-RISC"/>
 *     &lt;enumeration value="MIPS"/>
 *     &lt;enumeration value="Motorola 68k"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProcessorArchEnum", namespace = "http://cybox.mitre.org/objects#SystemObject-2")
@XmlEnum
public enum ProcessorArchEnum {


    /**
     * Specifies the 32-bit x86 architecture.
     * 
     */
    @XmlEnumValue("x86-32")
    X_86_32("x86-32"),

    /**
     * Specifies the 64-bit x86 architecture.
     * 
     */
    @XmlEnumValue("x86-64")
    X_86_64("x86-64"),

    /**
     * Specifies the 64-bit IA (Itanium) architecture.
     * 
     */
    @XmlEnumValue("IA-64")
    IA_64("IA-64"),

    /**
     * Specifies the PowerPC IA (Itanium) architecture.
     * 
     */
    @XmlEnumValue("PowerPC")
    POWER_PC("PowerPC"),

    /**
     * Specifies the ARM architecture.
     * 
     */
    ARM("ARM"),

    /**
     * Specifies the Alpha architecture.
     * 
     */
    @XmlEnumValue("Alpha")
    ALPHA("Alpha"),

    /**
     * Specifies the SPARC architecture.
     * 
     */
    SPARC("SPARC"),

    /**
     * Specifies the z/architecture, used on IBM mainframes.
     * 
     */
    @XmlEnumValue("z/Architecture")
    Z_ARCHITECTURE("z/Architecture"),

    /**
     * Specifies the eSi-RISC architecture.
     * 
     */
    @XmlEnumValue("eSi-RISC")
    E_SI_RISC("eSi-RISC"),

    /**
     * Specifies the MIPS architecture.
     * 
     */
    MIPS("MIPS"),

    /**
     * Specifies the Motorola 68k architecture.
     * 
     */
    @XmlEnumValue("Motorola 68k")
    MOTOROLA_68_K("Motorola 68k"),

    /**
     * Specifies a processor architecture other than those defined in this enumeration.
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ProcessorArchEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProcessorArchEnum fromValue(String v) {
        for (ProcessorArchEnum c: ProcessorArchEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
