//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Routers send Redirect packets to inform a host of a better first-hop node on the path to a destination. Hosts can be redirected to a better first-hop router but can also be informed by a redirect that the destination is in fact a neighbor. The latter is accomplished by setting the ICMP Target Address equal to the ICMP Destination Address. (type=137; code=0).
 * 
 * <p>Java class for RedirectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RedirectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Target_IPv6_Addr" type="{http://cybox.mitre.org/objects#AddressObject-2}AddressObjectType" minOccurs="0"/>
 *         &lt;element name="Dest_IPv6_Addr" type="{http://cybox.mitre.org/objects#AddressObject-2}AddressObjectType" minOccurs="0"/>
 *         &lt;element name="Options" type="{http://cybox.mitre.org/objects#PacketObject-2}RedirectOptionsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RedirectType", propOrder = {
    "targetIPv6Addr",
    "destIPv6Addr",
    "options"
})
public class RedirectType {

    @XmlElement(name = "Target_IPv6_Addr")
    protected Address targetIPv6Addr;
    @XmlElement(name = "Dest_IPv6_Addr")
    protected Address destIPv6Addr;
    @XmlElement(name = "Options")
    protected RedirectOptionsType options;

    /**
     * Gets the value of the targetIPv6Addr property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getTargetIPv6Addr() {
        return targetIPv6Addr;
    }

    /**
     * Sets the value of the targetIPv6Addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setTargetIPv6Addr(Address value) {
        this.targetIPv6Addr = value;
    }

    /**
     * Gets the value of the destIPv6Addr property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getDestIPv6Addr() {
        return destIPv6Addr;
    }

    /**
     * Sets the value of the destIPv6Addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setDestIPv6Addr(Address value) {
        this.destIPv6Addr = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link RedirectOptionsType }
     *     
     */
    public RedirectOptionsType getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedirectOptionsType }
     *     
     */
    public void setOptions(RedirectOptionsType value) {
        this.options = value;
    }

}
