//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.HexBinaryObjectPropertyType;
import org.mitre.cybox.common_2.IntegerObjectPropertyType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * Specifies the fields of the Routing header, which is used by an IPv6 source to list one or more intermediate nodes to be "visited" on the way to a packet's destination. http://tools.ietf.org/html/rfc2460.
 * 
 * <p>Java class for RoutingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RoutingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Next_Header" type="{http://cybox.mitre.org/objects#PacketObject-2}IANAAssignedIPNumbersType" minOccurs="0"/>
 *         &lt;element name="Header_Ext_Len" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Routing_Type" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Segments_Left" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Type_Specific_Data" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoutingType", propOrder = {
    "nextHeader",
    "headerExtLen",
    "routingType",
    "segmentsLeft",
    "typeSpecificData"
})
public class RoutingType {

    @XmlElement(name = "Next_Header")
    protected IANAAssignedIPNumbersType nextHeader;
    @XmlElement(name = "Header_Ext_Len")
    protected IntegerObjectPropertyType headerExtLen;
    @XmlElement(name = "Routing_Type")
    protected HexBinaryObjectPropertyType routingType;
    @XmlElement(name = "Segments_Left")
    protected IntegerObjectPropertyType segmentsLeft;
    @XmlElement(name = "Type_Specific_Data")
    protected StringObjectPropertyType typeSpecificData;

    /**
     * Gets the value of the nextHeader property.
     * 
     * @return
     *     possible object is
     *     {@link IANAAssignedIPNumbersType }
     *     
     */
    public IANAAssignedIPNumbersType getNextHeader() {
        return nextHeader;
    }

    /**
     * Sets the value of the nextHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link IANAAssignedIPNumbersType }
     *     
     */
    public void setNextHeader(IANAAssignedIPNumbersType value) {
        this.nextHeader = value;
    }

    /**
     * Gets the value of the headerExtLen property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public IntegerObjectPropertyType getHeaderExtLen() {
        return headerExtLen;
    }

    /**
     * Sets the value of the headerExtLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public void setHeaderExtLen(IntegerObjectPropertyType value) {
        this.headerExtLen = value;
    }

    /**
     * Gets the value of the routingType property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getRoutingType() {
        return routingType;
    }

    /**
     * Sets the value of the routingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setRoutingType(HexBinaryObjectPropertyType value) {
        this.routingType = value;
    }

    /**
     * Gets the value of the segmentsLeft property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public IntegerObjectPropertyType getSegmentsLeft() {
        return segmentsLeft;
    }

    /**
     * Sets the value of the segmentsLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public void setSegmentsLeft(IntegerObjectPropertyType value) {
        this.segmentsLeft = value;
    }

    /**
     * Gets the value of the typeSpecificData property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getTypeSpecificData() {
        return typeSpecificData;
    }

    /**
     * Sets the value of the typeSpecificData property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setTypeSpecificData(StringObjectPropertyType value) {
        this.typeSpecificData = value;
    }

}
