//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * Defines elements associated with a SiLK sensor.
 * 
 * <p>Java class for SiLKSensorInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SiLKSensorInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sensor_ID" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Class" type="{http://cybox.mitre.org/objects#NetworkFlowObject-2}SiLKSensorClassType" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://cybox.mitre.org/objects#NetworkFlowObject-2}SiLKDirectionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SiLKSensorInfoType", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", propOrder = {
    "sensorID",
    "clazz",
    "type"
})
public class SiLKSensorInfoType {

    @XmlElement(name = "Sensor_ID")
    protected StringObjectPropertyType sensorID;
    @XmlElement(name = "Class")
    protected SiLKSensorClassType clazz;
    @XmlElement(name = "Type")
    protected SiLKDirectionType type;

    /**
     * Gets the value of the sensorID property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getSensorID() {
        return sensorID;
    }

    /**
     * Sets the value of the sensorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setSensorID(StringObjectPropertyType value) {
        this.sensorID = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link SiLKSensorClassType }
     *     
     */
    public SiLKSensorClassType getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiLKSensorClassType }
     *     
     */
    public void setClazz(SiLKSensorClassType value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SiLKDirectionType }
     *     
     */
    public SiLKDirectionType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiLKDirectionType }
     *     
     */
    public void setType(SiLKDirectionType value) {
        this.type = value;
    }

}
