//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThreadRunningStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ThreadRunningStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Initialized"/>
 *     &lt;enumeration value="Ready"/>
 *     &lt;enumeration value="Running"/>
 *     &lt;enumeration value="Standby"/>
 *     &lt;enumeration value="Terminated"/>
 *     &lt;enumeration value="Waiting"/>
 *     &lt;enumeration value="Transition"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ThreadRunningStatusEnum", namespace = "http://cybox.mitre.org/objects#WinThreadObject-2")
@XmlEnum
public enum ThreadRunningStatusEnum {


    /**
     * A state that indicates the thread has been initialized, but has not yet started.
     * 
     */
    @XmlEnumValue("Initialized")
    INITIALIZED("Initialized"),

    /**
     * A state that indicates the thread is waiting to use a processor because no processor is free. The thread is prepared to run on the next available processor.
     * 
     */
    @XmlEnumValue("Ready")
    READY("Ready"),

    /**
     * A state that indicates the thread is currently using a processor.
     * 
     */
    @XmlEnumValue("Running")
    RUNNING("Running"),

    /**
     * A state that indicates the thread is about to use a processor. Only one thread can be in this state at a time.
     * 
     */
    @XmlEnumValue("Standby")
    STANDBY("Standby"),

    /**
     * A state that indicates the thread has finished executing and has exited.
     * 
     */
    @XmlEnumValue("Terminated")
    TERMINATED("Terminated"),

    /**
     * A state that indicates the thread is not ready to use the processor because it is waiting for a peripheral operation to complete or a resource to become free. When the thread is ready, it will be rescheduled.
     * 
     */
    @XmlEnumValue("Waiting")
    WAITING("Waiting"),

    /**
     * A state that indicates the thread is waiting for a resource, other than the processor, before it can execute.
     * 
     */
    @XmlEnumValue("Transition")
    TRANSITION("Transition"),

    /**
     * The thread of the thread is unknown.
     * 
     */
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    ThreadRunningStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ThreadRunningStatusEnum fromValue(String v) {
        for (ThreadRunningStatusEnum c: ThreadRunningStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
