//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.StringObjectPropertyType;
import org.mitre.cybox.common_2.UnsignedIntegerObjectPropertyType;


/**
 * The UnixUserAccountType type is intended to characterize Unix user accounts.
 * 
 * <p>Java class for UnixUserAccountObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnixUserAccountObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/objects#UserAccountObject-2}UserAccountObjectType">
 *       &lt;sequence>
 *         &lt;element name="Group_ID" type="{http://cybox.mitre.org/common-2}UnsignedIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="User_ID" type="{http://cybox.mitre.org/common-2}UnsignedIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Login_Shell" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnixUserAccountObjectType", namespace = "http://cybox.mitre.org/objects#UnixUserAccountObject-2", propOrder = {
    "groupID",
    "userID",
    "loginShell"
})
@XmlRootElement(name = "Unix_User_Account", namespace = "http://cybox.mitre.org/objects#UnixUserAccountObject-2")
public class UnixUserAccount
    extends UserAccountObjectType
{

    @XmlElement(name = "Group_ID")
    protected UnsignedIntegerObjectPropertyType groupID;
    @XmlElement(name = "User_ID")
    protected UnsignedIntegerObjectPropertyType userID;
    @XmlElement(name = "Login_Shell")
    protected StringObjectPropertyType loginShell;

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedIntegerObjectPropertyType }
     *     
     */
    public UnsignedIntegerObjectPropertyType getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedIntegerObjectPropertyType }
     *     
     */
    public void setGroupID(UnsignedIntegerObjectPropertyType value) {
        this.groupID = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link UnsignedIntegerObjectPropertyType }
     *     
     */
    public UnsignedIntegerObjectPropertyType getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnsignedIntegerObjectPropertyType }
     *     
     */
    public void setUserID(UnsignedIntegerObjectPropertyType value) {
        this.userID = value;
    }

    /**
     * Gets the value of the loginShell property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getLoginShell() {
        return loginShell;
    }

    /**
     * Sets the value of the loginShell property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setLoginShell(StringObjectPropertyType value) {
        this.loginShell = value;
    }

}
