//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.HexBinaryObjectPropertyType;
import org.mitre.cybox.common_2.NonNegativeIntegerObjectPropertyType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The WindowsPipeObjectType type is intended to characterize Windows pipes.
 * 
 * <p>Java class for WindowsPipeObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindowsPipeObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/objects#PipeObject-2}PipeObjectType">
 *       &lt;sequence>
 *         &lt;element name="Default_Time_Out" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Handle" type="{http://cybox.mitre.org/objects#WinHandleObject-2}WindowsHandleObjectType" minOccurs="0"/>
 *         &lt;element name="In_Buffer_Size" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Max_Instances" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Open_Mode" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Out_Buffer_Size" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0" form="qualified"/>
 *         &lt;element name="Pipe_Mode" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Security_Attributes" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindowsPipeObjectType", namespace = "http://cybox.mitre.org/objects#WinPipeObject-2", propOrder = {
    "defaultTimeOut",
    "handle",
    "inBufferSize",
    "maxInstances",
    "openMode",
    "outBufferSize",
    "pipeMode",
    "securityAttributes"
})
@XmlRootElement(name = "Windows_Pipe", namespace = "http://cybox.mitre.org/objects#WinPipeObject-2")
public class WindowsPipe
    extends PipeObjectType
{

    @XmlElement(name = "Default_Time_Out")
    protected NonNegativeIntegerObjectPropertyType defaultTimeOut;
    @XmlElement(name = "Handle")
    protected WindowsHandle handle;
    @XmlElement(name = "In_Buffer_Size")
    protected NonNegativeIntegerObjectPropertyType inBufferSize;
    @XmlElement(name = "Max_Instances")
    protected NonNegativeIntegerObjectPropertyType maxInstances;
    @XmlElement(name = "Open_Mode")
    protected HexBinaryObjectPropertyType openMode;
    @XmlElement(name = "Out_Buffer_Size")
    protected NonNegativeIntegerObjectPropertyType outBufferSize;
    @XmlElement(name = "Pipe_Mode")
    protected HexBinaryObjectPropertyType pipeMode;
    @XmlElement(name = "Security_Attributes")
    protected StringObjectPropertyType securityAttributes;

    /**
     * Gets the value of the defaultTimeOut property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getDefaultTimeOut() {
        return defaultTimeOut;
    }

    /**
     * Sets the value of the defaultTimeOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setDefaultTimeOut(NonNegativeIntegerObjectPropertyType value) {
        this.defaultTimeOut = value;
    }

    /**
     * Gets the value of the handle property.
     * 
     * @return
     *     possible object is
     *     {@link WindowsHandle }
     *     
     */
    public WindowsHandle getHandle() {
        return handle;
    }

    /**
     * Sets the value of the handle property.
     * 
     * @param value
     *     allowed object is
     *     {@link WindowsHandle }
     *     
     */
    public void setHandle(WindowsHandle value) {
        this.handle = value;
    }

    /**
     * Gets the value of the inBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getInBufferSize() {
        return inBufferSize;
    }

    /**
     * Sets the value of the inBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setInBufferSize(NonNegativeIntegerObjectPropertyType value) {
        this.inBufferSize = value;
    }

    /**
     * Gets the value of the maxInstances property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getMaxInstances() {
        return maxInstances;
    }

    /**
     * Sets the value of the maxInstances property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setMaxInstances(NonNegativeIntegerObjectPropertyType value) {
        this.maxInstances = value;
    }

    /**
     * Gets the value of the openMode property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getOpenMode() {
        return openMode;
    }

    /**
     * Sets the value of the openMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setOpenMode(HexBinaryObjectPropertyType value) {
        this.openMode = value;
    }

    /**
     * Gets the value of the outBufferSize property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getOutBufferSize() {
        return outBufferSize;
    }

    /**
     * Sets the value of the outBufferSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setOutBufferSize(NonNegativeIntegerObjectPropertyType value) {
        this.outBufferSize = value;
    }

    /**
     * Gets the value of the pipeMode property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getPipeMode() {
        return pipeMode;
    }

    /**
     * Sets the value of the pipeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setPipeMode(HexBinaryObjectPropertyType value) {
        this.pipeMode = value;
    }

    /**
     * Gets the value of the securityAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getSecurityAttributes() {
        return securityAttributes;
    }

    /**
     * Sets the value of the securityAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setSecurityAttributes(StringObjectPropertyType value) {
        this.securityAttributes = value;
    }

}
