//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.HashListType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The WindowsServiceObjectType type is intended to characterize Windows services.
 * 
 * <p>Java class for WindowsServiceObjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WindowsServiceObjectType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://cybox.mitre.org/objects#WinProcessObject-2}WindowsProcessObjectType">
 *       &lt;sequence>
 *         &lt;element name="Description_List" type="{http://cybox.mitre.org/objects#WinServiceObject-2}ServiceDescriptionListType" minOccurs="0"/>
 *         &lt;element name="Display_Name" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Group_Name" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Service_Name" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Service_DLL" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Service_DLL_Certificate_Issuer" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Service_DLL_Certificate_Subject" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Service_DLL_Hashes" type="{http://cybox.mitre.org/common-2}HashListType" minOccurs="0"/>
 *         &lt;element name="Service_DLL_Signature_Description" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Startup_Command_Line" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Startup_Type" type="{http://cybox.mitre.org/objects#WinServiceObject-2}ServiceModeType" minOccurs="0"/>
 *         &lt;element name="Service_Status" type="{http://cybox.mitre.org/objects#WinServiceObject-2}ServiceStatusType" minOccurs="0"/>
 *         &lt;element name="Service_Type" type="{http://cybox.mitre.org/objects#WinServiceObject-2}ServiceType" minOccurs="0"/>
 *         &lt;element name="Started_As" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="service_dll_signature_exists" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="service_dll_signature_verified" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WindowsServiceObjectType", namespace = "http://cybox.mitre.org/objects#WinServiceObject-2", propOrder = {
    "descriptionList",
    "displayName",
    "groupName",
    "serviceName",
    "serviceDLL",
    "serviceDLLCertificateIssuer",
    "serviceDLLCertificateSubject",
    "serviceDLLHashes",
    "serviceDLLSignatureDescription",
    "startupCommandLine",
    "startupType",
    "serviceStatus",
    "serviceType",
    "startedAs"
})
@XmlRootElement(name = "Windows_Service", namespace = "http://cybox.mitre.org/objects#WinServiceObject-2")
public class WindowsService
    extends WindowsProcessObjectType
{

    @XmlElement(name = "Description_List")
    protected ServiceDescriptionListType descriptionList;
    @XmlElement(name = "Display_Name")
    protected StringObjectPropertyType displayName;
    @XmlElement(name = "Group_Name")
    protected StringObjectPropertyType groupName;
    @XmlElement(name = "Service_Name")
    protected StringObjectPropertyType serviceName;
    @XmlElement(name = "Service_DLL")
    protected StringObjectPropertyType serviceDLL;
    @XmlElement(name = "Service_DLL_Certificate_Issuer")
    protected StringObjectPropertyType serviceDLLCertificateIssuer;
    @XmlElement(name = "Service_DLL_Certificate_Subject")
    protected StringObjectPropertyType serviceDLLCertificateSubject;
    @XmlElement(name = "Service_DLL_Hashes")
    protected HashListType serviceDLLHashes;
    @XmlElement(name = "Service_DLL_Signature_Description")
    protected StringObjectPropertyType serviceDLLSignatureDescription;
    @XmlElement(name = "Startup_Command_Line")
    protected StringObjectPropertyType startupCommandLine;
    @XmlElement(name = "Startup_Type")
    protected ServiceModeType startupType;
    @XmlElement(name = "Service_Status")
    protected ServiceStatusType serviceStatus;
    @XmlElement(name = "Service_Type")
    protected ServiceType serviceType;
    @XmlElement(name = "Started_As")
    protected StringObjectPropertyType startedAs;
    @XmlAttribute(name = "service_dll_signature_exists")
    protected Boolean serviceDllSignatureExists;
    @XmlAttribute(name = "service_dll_signature_verified")
    protected Boolean serviceDllSignatureVerified;

    /**
     * Gets the value of the descriptionList property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceDescriptionListType }
     *     
     */
    public ServiceDescriptionListType getDescriptionList() {
        return descriptionList;
    }

    /**
     * Sets the value of the descriptionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceDescriptionListType }
     *     
     */
    public void setDescriptionList(ServiceDescriptionListType value) {
        this.descriptionList = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setDisplayName(StringObjectPropertyType value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the groupName property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getGroupName() {
        return groupName;
    }

    /**
     * Sets the value of the groupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setGroupName(StringObjectPropertyType value) {
        this.groupName = value;
    }

    /**
     * Gets the value of the serviceName property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getServiceName() {
        return serviceName;
    }

    /**
     * Sets the value of the serviceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setServiceName(StringObjectPropertyType value) {
        this.serviceName = value;
    }

    /**
     * Gets the value of the serviceDLL property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getServiceDLL() {
        return serviceDLL;
    }

    /**
     * Sets the value of the serviceDLL property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setServiceDLL(StringObjectPropertyType value) {
        this.serviceDLL = value;
    }

    /**
     * Gets the value of the serviceDLLCertificateIssuer property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getServiceDLLCertificateIssuer() {
        return serviceDLLCertificateIssuer;
    }

    /**
     * Sets the value of the serviceDLLCertificateIssuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setServiceDLLCertificateIssuer(StringObjectPropertyType value) {
        this.serviceDLLCertificateIssuer = value;
    }

    /**
     * Gets the value of the serviceDLLCertificateSubject property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getServiceDLLCertificateSubject() {
        return serviceDLLCertificateSubject;
    }

    /**
     * Sets the value of the serviceDLLCertificateSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setServiceDLLCertificateSubject(StringObjectPropertyType value) {
        this.serviceDLLCertificateSubject = value;
    }

    /**
     * Gets the value of the serviceDLLHashes property.
     * 
     * @return
     *     possible object is
     *     {@link HashListType }
     *     
     */
    public HashListType getServiceDLLHashes() {
        return serviceDLLHashes;
    }

    /**
     * Sets the value of the serviceDLLHashes property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashListType }
     *     
     */
    public void setServiceDLLHashes(HashListType value) {
        this.serviceDLLHashes = value;
    }

    /**
     * Gets the value of the serviceDLLSignatureDescription property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getServiceDLLSignatureDescription() {
        return serviceDLLSignatureDescription;
    }

    /**
     * Sets the value of the serviceDLLSignatureDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setServiceDLLSignatureDescription(StringObjectPropertyType value) {
        this.serviceDLLSignatureDescription = value;
    }

    /**
     * Gets the value of the startupCommandLine property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getStartupCommandLine() {
        return startupCommandLine;
    }

    /**
     * Sets the value of the startupCommandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setStartupCommandLine(StringObjectPropertyType value) {
        this.startupCommandLine = value;
    }

    /**
     * Gets the value of the startupType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceModeType }
     *     
     */
    public ServiceModeType getStartupType() {
        return startupType;
    }

    /**
     * Sets the value of the startupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceModeType }
     *     
     */
    public void setStartupType(ServiceModeType value) {
        this.startupType = value;
    }

    /**
     * Gets the value of the serviceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceStatusType }
     *     
     */
    public ServiceStatusType getServiceStatus() {
        return serviceStatus;
    }

    /**
     * Sets the value of the serviceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceStatusType }
     *     
     */
    public void setServiceStatus(ServiceStatusType value) {
        this.serviceStatus = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setServiceType(ServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the startedAs property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getStartedAs() {
        return startedAs;
    }

    /**
     * Sets the value of the startedAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setStartedAs(StringObjectPropertyType value) {
        this.startedAs = value;
    }

    /**
     * Gets the value of the serviceDllSignatureExists property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServiceDllSignatureExists() {
        return serviceDllSignatureExists;
    }

    /**
     * Sets the value of the serviceDllSignatureExists property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServiceDllSignatureExists(Boolean value) {
        this.serviceDllSignatureExists = value;
    }

    /**
     * Gets the value of the serviceDllSignatureVerified property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isServiceDllSignatureVerified() {
        return serviceDllSignatureVerified;
    }

    /**
     * Sets the value of the serviceDllSignatureVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setServiceDllSignatureVerified(Boolean value) {
        this.serviceDllSignatureVerified = value;
    }

}
