//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.NonNegativeIntegerObjectPropertyType;
import org.mitre.cybox.common_2.StringObjectPropertyType;


/**
 * The X509V3ExtensionsType captures the standard X509 V3 Extensions that may be used in X509 certificates. Based on RFC 3280, "Standard Extensions": http://www.ietf.org/rfc/rfc3280.txt.
 * 
 * <p>Java class for X509V3ExtensionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="X509V3ExtensionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Basic_Constraints" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Name_Constraints" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Policy_Constraints" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Key_Usage" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Extended_Key_Usage" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Subject_Key_Identifier" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Authority_Key_Identifier" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Subject_Alternative_Name" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Issuer_Alternative_Name" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Subject_Directory_Attributes" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="CRL_Distribution_Points" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Inhibit_Any_Policy" type="{http://cybox.mitre.org/common-2}NonNegativeIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Private_Key_Usage_Period" type="{http://cybox.mitre.org/objects#X509CertificateObject-2}ValidityType" minOccurs="0"/>
 *         &lt;element name="Certificate_Policies" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Policy_Mappings" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "X509V3ExtensionsType", namespace = "http://cybox.mitre.org/objects#X509CertificateObject-2", propOrder = {
    "basicConstraints",
    "nameConstraints",
    "policyConstraints",
    "keyUsage",
    "extendedKeyUsage",
    "subjectKeyIdentifier",
    "authorityKeyIdentifier",
    "subjectAlternativeName",
    "issuerAlternativeName",
    "subjectDirectoryAttributes",
    "crlDistributionPoints",
    "inhibitAnyPolicy",
    "privateKeyUsagePeriod",
    "certificatePolicies",
    "policyMappings"
})
public class X509V3ExtensionsType {

    @XmlElement(name = "Basic_Constraints")
    protected StringObjectPropertyType basicConstraints;
    @XmlElement(name = "Name_Constraints")
    protected StringObjectPropertyType nameConstraints;
    @XmlElement(name = "Policy_Constraints")
    protected StringObjectPropertyType policyConstraints;
    @XmlElement(name = "Key_Usage")
    protected StringObjectPropertyType keyUsage;
    @XmlElement(name = "Extended_Key_Usage")
    protected StringObjectPropertyType extendedKeyUsage;
    @XmlElement(name = "Subject_Key_Identifier")
    protected StringObjectPropertyType subjectKeyIdentifier;
    @XmlElement(name = "Authority_Key_Identifier")
    protected StringObjectPropertyType authorityKeyIdentifier;
    @XmlElement(name = "Subject_Alternative_Name")
    protected StringObjectPropertyType subjectAlternativeName;
    @XmlElement(name = "Issuer_Alternative_Name")
    protected StringObjectPropertyType issuerAlternativeName;
    @XmlElement(name = "Subject_Directory_Attributes")
    protected StringObjectPropertyType subjectDirectoryAttributes;
    @XmlElement(name = "CRL_Distribution_Points")
    protected StringObjectPropertyType crlDistributionPoints;
    @XmlElement(name = "Inhibit_Any_Policy")
    protected NonNegativeIntegerObjectPropertyType inhibitAnyPolicy;
    @XmlElement(name = "Private_Key_Usage_Period")
    protected ValidityType privateKeyUsagePeriod;
    @XmlElement(name = "Certificate_Policies")
    protected StringObjectPropertyType certificatePolicies;
    @XmlElement(name = "Policy_Mappings")
    protected StringObjectPropertyType policyMappings;

    /**
     * Gets the value of the basicConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getBasicConstraints() {
        return basicConstraints;
    }

    /**
     * Sets the value of the basicConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setBasicConstraints(StringObjectPropertyType value) {
        this.basicConstraints = value;
    }

    /**
     * Gets the value of the nameConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getNameConstraints() {
        return nameConstraints;
    }

    /**
     * Sets the value of the nameConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setNameConstraints(StringObjectPropertyType value) {
        this.nameConstraints = value;
    }

    /**
     * Gets the value of the policyConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getPolicyConstraints() {
        return policyConstraints;
    }

    /**
     * Sets the value of the policyConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setPolicyConstraints(StringObjectPropertyType value) {
        this.policyConstraints = value;
    }

    /**
     * Gets the value of the keyUsage property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getKeyUsage() {
        return keyUsage;
    }

    /**
     * Sets the value of the keyUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setKeyUsage(StringObjectPropertyType value) {
        this.keyUsage = value;
    }

    /**
     * Gets the value of the extendedKeyUsage property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getExtendedKeyUsage() {
        return extendedKeyUsage;
    }

    /**
     * Sets the value of the extendedKeyUsage property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setExtendedKeyUsage(StringObjectPropertyType value) {
        this.extendedKeyUsage = value;
    }

    /**
     * Gets the value of the subjectKeyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getSubjectKeyIdentifier() {
        return subjectKeyIdentifier;
    }

    /**
     * Sets the value of the subjectKeyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setSubjectKeyIdentifier(StringObjectPropertyType value) {
        this.subjectKeyIdentifier = value;
    }

    /**
     * Gets the value of the authorityKeyIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getAuthorityKeyIdentifier() {
        return authorityKeyIdentifier;
    }

    /**
     * Sets the value of the authorityKeyIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setAuthorityKeyIdentifier(StringObjectPropertyType value) {
        this.authorityKeyIdentifier = value;
    }

    /**
     * Gets the value of the subjectAlternativeName property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getSubjectAlternativeName() {
        return subjectAlternativeName;
    }

    /**
     * Sets the value of the subjectAlternativeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setSubjectAlternativeName(StringObjectPropertyType value) {
        this.subjectAlternativeName = value;
    }

    /**
     * Gets the value of the issuerAlternativeName property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getIssuerAlternativeName() {
        return issuerAlternativeName;
    }

    /**
     * Sets the value of the issuerAlternativeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setIssuerAlternativeName(StringObjectPropertyType value) {
        this.issuerAlternativeName = value;
    }

    /**
     * Gets the value of the subjectDirectoryAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getSubjectDirectoryAttributes() {
        return subjectDirectoryAttributes;
    }

    /**
     * Sets the value of the subjectDirectoryAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setSubjectDirectoryAttributes(StringObjectPropertyType value) {
        this.subjectDirectoryAttributes = value;
    }

    /**
     * Gets the value of the crlDistributionPoints property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getCRLDistributionPoints() {
        return crlDistributionPoints;
    }

    /**
     * Sets the value of the crlDistributionPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setCRLDistributionPoints(StringObjectPropertyType value) {
        this.crlDistributionPoints = value;
    }

    /**
     * Gets the value of the inhibitAnyPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public NonNegativeIntegerObjectPropertyType getInhibitAnyPolicy() {
        return inhibitAnyPolicy;
    }

    /**
     * Sets the value of the inhibitAnyPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonNegativeIntegerObjectPropertyType }
     *     
     */
    public void setInhibitAnyPolicy(NonNegativeIntegerObjectPropertyType value) {
        this.inhibitAnyPolicy = value;
    }

    /**
     * Gets the value of the privateKeyUsagePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ValidityType }
     *     
     */
    public ValidityType getPrivateKeyUsagePeriod() {
        return privateKeyUsagePeriod;
    }

    /**
     * Sets the value of the privateKeyUsagePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidityType }
     *     
     */
    public void setPrivateKeyUsagePeriod(ValidityType value) {
        this.privateKeyUsagePeriod = value;
    }

    /**
     * Gets the value of the certificatePolicies property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getCertificatePolicies() {
        return certificatePolicies;
    }

    /**
     * Sets the value of the certificatePolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setCertificatePolicies(StringObjectPropertyType value) {
        this.certificatePolicies = value;
    }

    /**
     * Gets the value of the policyMappings property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getPolicyMappings() {
        return policyMappings;
    }

    /**
     * Sets the value of the policyMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setPolicyMappings(StringObjectPropertyType value) {
        this.policyMappings = value;
    }

}
