//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.common_2.HexBinaryObjectPropertyType;
import org.mitre.cybox.common_2.IntegerObjectPropertyType;


/**
 * Contains TCP-related information of the network flow.
 * 
 * <p>Java class for YAFTCPFlowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="YAFTCPFlowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TCP_Sequence_Number" type="{http://cybox.mitre.org/common-2}IntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Initial_TCP_Flags" type="{http://cybox.mitre.org/objects#PacketObject-2}TCPFlagsType" minOccurs="0"/>
 *         &lt;element name="Union_TCP_Flags" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "YAFTCPFlowType", namespace = "http://cybox.mitre.org/objects#NetworkFlowObject-2", propOrder = {
    "tcpSequenceNumber",
    "initialTCPFlags",
    "unionTCPFlags"
})
public class YAFTCPFlowType {

    @XmlElement(name = "TCP_Sequence_Number")
    protected IntegerObjectPropertyType tcpSequenceNumber;
    @XmlElement(name = "Initial_TCP_Flags")
    protected TCPFlagsType initialTCPFlags;
    @XmlElement(name = "Union_TCP_Flags")
    protected HexBinaryObjectPropertyType unionTCPFlags;

    /**
     * Gets the value of the tcpSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public IntegerObjectPropertyType getTCPSequenceNumber() {
        return tcpSequenceNumber;
    }

    /**
     * Sets the value of the tcpSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerObjectPropertyType }
     *     
     */
    public void setTCPSequenceNumber(IntegerObjectPropertyType value) {
        this.tcpSequenceNumber = value;
    }

    /**
     * Gets the value of the initialTCPFlags property.
     * 
     * @return
     *     possible object is
     *     {@link TCPFlagsType }
     *     
     */
    public TCPFlagsType getInitialTCPFlags() {
        return initialTCPFlags;
    }

    /**
     * Sets the value of the initialTCPFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCPFlagsType }
     *     
     */
    public void setInitialTCPFlags(TCPFlagsType value) {
        this.initialTCPFlags = value;
    }

    /**
     * Gets the value of the unionTCPFlags property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getUnionTCPFlags() {
        return unionTCPFlags;
    }

    /**
     * Sets the value of the unionTCPFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setUnionTCPFlags(HexBinaryObjectPropertyType value) {
        this.unionTCPFlags = value;
    }

}
