//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.common_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The CompilerInformalDescriptionType contains the informal description of this compiler instance.
 * 
 * <p>Java class for CompilerInformalDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompilerInformalDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Compiler_Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Compiler_Version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompilerInformalDescriptionType", propOrder = {
    "compilerName",
    "compilerVersion"
})
public class CompilerInformalDescriptionType {

    @XmlElement(name = "Compiler_Name", required = true)
    protected String compilerName;
    @XmlElement(name = "Compiler_Version")
    protected String compilerVersion;

    /**
     * Gets the value of the compilerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompilerName() {
        return compilerName;
    }

    /**
     * Sets the value of the compilerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompilerName(String value) {
        this.compilerName = value;
    }

    /**
     * Gets the value of the compilerVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompilerVersion() {
        return compilerVersion;
    }

    /**
     * Sets the value of the compilerVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompilerVersion(String value) {
        this.compilerVersion = value;
    }

}
