//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.common_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.mitre.cybox.default_vocabularies_2.ActionArgumentNameVocab10;
import org.mitre.cybox.default_vocabularies_2.ActionNameVocab10;
import org.mitre.cybox.default_vocabularies_2.ActionNameVocab11;
import org.mitre.cybox.default_vocabularies_2.ActionObjectAssociationTypeVocab10;
import org.mitre.cybox.default_vocabularies_2.ActionRelationshipTypeVocab10;
import org.mitre.cybox.default_vocabularies_2.ActionTypeVocab10;
import org.mitre.cybox.default_vocabularies_2.CharacterEncodingVocab10;
import org.mitre.cybox.default_vocabularies_2.EventTypeVocab10;
import org.mitre.cybox.default_vocabularies_2.EventTypeVocab101;
import org.mitre.cybox.default_vocabularies_2.HashNameVocab10;
import org.mitre.cybox.default_vocabularies_2.InformationSourceTypeVocab10;
import org.mitre.cybox.default_vocabularies_2.ObjectRelationshipVocab10;
import org.mitre.cybox.default_vocabularies_2.ObjectRelationshipVocab11;
import org.mitre.cybox.default_vocabularies_2.ObjectStateVocab10;
import org.mitre.cybox.default_vocabularies_2.ToolTypeVocab10;
import org.mitre.cybox.default_vocabularies_2.ToolTypeVocab11;
import org.mitre.cybox.objects.AuthenticationTokenProtectionMechanismTypeVocab10;
import org.mitre.cybox.objects.AuthenticationTypeVocab10;
import org.mitre.stix.default_vocabularies_1.AttackerToolTypeVocab10;


/**
 * The ControlledVocabularyStringType is used as the basis for defining controlled vocabularies.
 * 
 * <p>Java class for ControlledVocabularyStringType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlledVocabularyStringType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://cybox.mitre.org/common-2>PatternableFieldType">
 *       &lt;attribute name="vocab_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="vocab_reference" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlledVocabularyStringType")
@XmlSeeAlso({
    AuthenticationTokenProtectionMechanismTypeVocab10 .class,
    AuthenticationTypeVocab10 .class,
    ActionTypeVocab10 .class,
    ActionArgumentNameVocab10 .class,
    ObjectStateVocab10 .class,
    EventTypeVocab10 .class,
    InformationSourceTypeVocab10 .class,
    ActionNameVocab11 .class,
    ActionNameVocab10 .class,
    ToolTypeVocab11 .class,
    ActionObjectAssociationTypeVocab10 .class,
    CharacterEncodingVocab10 .class,
    EventTypeVocab101 .class,
    ToolTypeVocab10 .class,
    HashNameVocab10 .class,
    ActionRelationshipTypeVocab10 .class,
    ObjectRelationshipVocab11 .class,
    ObjectRelationshipVocab10 .class,
    AttackerToolTypeVocab10 .class
})
public class ControlledVocabularyStringType
    extends PatternableFieldType
{

    @XmlAttribute(name = "vocab_name")
    protected String vocabName;
    @XmlAttribute(name = "vocab_reference")
    @XmlSchemaType(name = "anyURI")
    protected String vocabReference;

    /**
     * Gets the value of the vocabName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocabName() {
        return vocabName;
    }

    /**
     * Sets the value of the vocabName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocabName(String value) {
        this.vocabName = value;
    }

    /**
     * Gets the value of the vocabReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocabReference() {
        return vocabReference;
    }

    /**
     * Sets the value of the vocabReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocabReference(String value) {
        this.vocabReference = value;
    }

}
