//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.common_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The ExtractedStringType type is intended as container a single string extracted from a CybOX object.
 * 
 * <p>Java class for ExtractedStringType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtractedStringType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Encoding" type="{http://cybox.mitre.org/common-2}ControlledVocabularyStringType" minOccurs="0"/>
 *         &lt;element name="String_Value" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Byte_String_Value" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Hashes" type="{http://cybox.mitre.org/common-2}HashListType" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://cybox.mitre.org/common-2}HexBinaryObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Length" type="{http://cybox.mitre.org/common-2}PositiveIntegerObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="Language" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *         &lt;element name="English_Translation" type="{http://cybox.mitre.org/common-2}StringObjectPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtractedStringType", propOrder = {
    "encoding",
    "stringValue",
    "byteStringValue",
    "hashes",
    "address",
    "length",
    "language",
    "englishTranslation"
})
public class ExtractedStringType {

    @XmlElement(name = "Encoding")
    protected ControlledVocabularyStringType encoding;
    @XmlElement(name = "String_Value")
    protected StringObjectPropertyType stringValue;
    @XmlElement(name = "Byte_String_Value")
    protected HexBinaryObjectPropertyType byteStringValue;
    @XmlElement(name = "Hashes")
    protected HashListType hashes;
    @XmlElement(name = "Address")
    protected HexBinaryObjectPropertyType address;
    @XmlElement(name = "Length")
    protected PositiveIntegerObjectPropertyType length;
    @XmlElement(name = "Language")
    protected StringObjectPropertyType language;
    @XmlElement(name = "English_Translation")
    protected StringObjectPropertyType englishTranslation;

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledVocabularyStringType }
     *     
     */
    public ControlledVocabularyStringType getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledVocabularyStringType }
     *     
     */
    public void setEncoding(ControlledVocabularyStringType value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the stringValue property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getStringValue() {
        return stringValue;
    }

    /**
     * Sets the value of the stringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setStringValue(StringObjectPropertyType value) {
        this.stringValue = value;
    }

    /**
     * Gets the value of the byteStringValue property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getByteStringValue() {
        return byteStringValue;
    }

    /**
     * Sets the value of the byteStringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setByteStringValue(HexBinaryObjectPropertyType value) {
        this.byteStringValue = value;
    }

    /**
     * Gets the value of the hashes property.
     * 
     * @return
     *     possible object is
     *     {@link HashListType }
     *     
     */
    public HashListType getHashes() {
        return hashes;
    }

    /**
     * Sets the value of the hashes property.
     * 
     * @param value
     *     allowed object is
     *     {@link HashListType }
     *     
     */
    public void setHashes(HashListType value) {
        this.hashes = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public HexBinaryObjectPropertyType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link HexBinaryObjectPropertyType }
     *     
     */
    public void setAddress(HexBinaryObjectPropertyType value) {
        this.address = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveIntegerObjectPropertyType }
     *     
     */
    public PositiveIntegerObjectPropertyType getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveIntegerObjectPropertyType }
     *     
     */
    public void setLength(PositiveIntegerObjectPropertyType value) {
        this.length = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setLanguage(StringObjectPropertyType value) {
        this.language = value;
    }

    /**
     * Gets the value of the englishTranslation property.
     * 
     * @return
     *     possible object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public StringObjectPropertyType getEnglishTranslation() {
        return englishTranslation;
    }

    /**
     * Sets the value of the englishTranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringObjectPropertyType }
     *     
     */
    public void setEnglishTranslation(StringObjectPropertyType value) {
        this.englishTranslation = value;
    }

}
