//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.common_2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The HashValueType is used for specifying the resulting value from a hash calculation.
 * 
 * <p>Java class for HashValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HashValueType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Simple_Hash_Value" type="{http://cybox.mitre.org/common-2}SimpleHashValueType" minOccurs="0"/>
 *         &lt;element name="Fuzzy_Hash_Value" type="{http://cybox.mitre.org/common-2}FuzzyHashValueType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HashValueType", propOrder = {
    "fuzzyHashValue",
    "simpleHashValue"
})
public class HashValueType {

    @XmlElement(name = "Fuzzy_Hash_Value")
    protected FuzzyHashValueType fuzzyHashValue;
    @XmlElement(name = "Simple_Hash_Value")
    protected SimpleHashValueType simpleHashValue;

    /**
     * Gets the value of the fuzzyHashValue property.
     * 
     * @return
     *     possible object is
     *     {@link FuzzyHashValueType }
     *     
     */
    public FuzzyHashValueType getFuzzyHashValue() {
        return fuzzyHashValue;
    }

    /**
     * Sets the value of the fuzzyHashValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuzzyHashValueType }
     *     
     */
    public void setFuzzyHashValue(FuzzyHashValueType value) {
        this.fuzzyHashValue = value;
    }

    /**
     * Gets the value of the simpleHashValue property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleHashValueType }
     *     
     */
    public SimpleHashValueType getSimpleHashValue() {
        return simpleHashValue;
    }

    /**
     * Sets the value of the simpleHashValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleHashValueType }
     *     
     */
    public void setSimpleHashValue(SimpleHashValueType value) {
        this.simpleHashValue = value;
    }

}
