//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.common_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SourceClassTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SourceClassTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Network"/>
 *     &lt;enumeration value="System"/>
 *     &lt;enumeration value="Software"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SourceClassTypeEnum")
@XmlEnum
public enum SourceClassTypeEnum {


    /**
     * Describes a Network-based cyber observation.
     * 
     */
    @XmlEnumValue("Network")
    NETWORK("Network"),

    /**
     * Describes a System-based cyber observation.
     * 
     */
    @XmlEnumValue("System")
    SYSTEM("System"),

    /**
     * Describes a Software-based cyber observation.
     * 
     */
    @XmlEnumValue("Software")
    SOFTWARE("Software");
    private final String value;

    SourceClassTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SourceClassTypeEnum fromValue(String v) {
        for (SourceClassTypeEnum c: SourceClassTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
