//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.cybox.common_2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ToolReferenceTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ToolReferenceTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Documentation"/>
 *     &lt;enumeration value="Source"/>
 *     &lt;enumeration value="Download"/>
 *     &lt;enumeration value="Execute"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ToolReferenceTypeEnum")
@XmlEnum
public enum ToolReferenceTypeEnum {


    /**
     * The reference is to documentation about the identified tool.
     * 
     */
    @XmlEnumValue("Documentation")
    DOCUMENTATION("Documentation"),

    /**
     * The reference is to source code for the identified tool.
     * 
     */
    @XmlEnumValue("Source")
    SOURCE("Source"),

    /**
     * The reference is to where an executable version of the tool can be downloaded.
     * 
     */
    @XmlEnumValue("Download")
    DOWNLOAD("Download"),

    /**
     * The reference is to the tool implemented as an online service.
     * 
     */
    @XmlEnumValue("Execute")
    EXECUTE("Execute"),

    /**
     * The reference is to material about the tool not covered by other values in this enumeration.
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ToolReferenceTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ToolReferenceTypeEnum fromValue(String v) {
        for (ToolReferenceTypeEnum c: ToolReferenceTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
