//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.stix.default_vocabularies_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttackerInfrastructureTypeEnum-1.0.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AttackerInfrastructureTypeEnum-1.0">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Anonymization"/>
 *     &lt;enumeration value="Anonymization - Proxy"/>
 *     &lt;enumeration value="Anonymization - TOR Network"/>
 *     &lt;enumeration value="Anonymization - VPN"/>
 *     &lt;enumeration value="Communications"/>
 *     &lt;enumeration value="Communications - Blogs"/>
 *     &lt;enumeration value="Communications - Forums"/>
 *     &lt;enumeration value="Communications - Internet Relay Chat"/>
 *     &lt;enumeration value="Communications - Micro-Blogs"/>
 *     &lt;enumeration value="Communications - Mobile Communications"/>
 *     &lt;enumeration value="Communications - Social Networks"/>
 *     &lt;enumeration value="Communications - User-Generated Content Websites"/>
 *     &lt;enumeration value="Domain Registration"/>
 *     &lt;enumeration value="Domain Registration - Dynamic DNS Services"/>
 *     &lt;enumeration value="Domain Registration - Legitimate Domain Registration Services"/>
 *     &lt;enumeration value="Domain Registration - Malicious Domain Registrars"/>
 *     &lt;enumeration value="Domain Registration - Top-Level Domain Registrars"/>
 *     &lt;enumeration value="Hosting"/>
 *     &lt;enumeration value="Hosting - Bulletproof / Rogue Hosting"/>
 *     &lt;enumeration value="Hosting - Cloud Hosting"/>
 *     &lt;enumeration value="Hosting - Compromised Server"/>
 *     &lt;enumeration value="Hosting - Fast Flux Botnet Hosting"/>
 *     &lt;enumeration value="Hosting - Legitimate Hosting"/>
 *     &lt;enumeration value="Electronic Payment Methods"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AttackerInfrastructureTypeEnum-1.0")
@XmlEnum
public enum AttackerInfrastructureTypeEnum10 {

    @XmlEnumValue("Anonymization")
    ANONYMIZATION("Anonymization"),
    @XmlEnumValue("Anonymization - Proxy")
    ANONYMIZATION_PROXY("Anonymization - Proxy"),
    @XmlEnumValue("Anonymization - TOR Network")
    ANONYMIZATION_TOR_NETWORK("Anonymization - TOR Network"),
    @XmlEnumValue("Anonymization - VPN")
    ANONYMIZATION_VPN("Anonymization - VPN"),
    @XmlEnumValue("Communications")
    COMMUNICATIONS("Communications"),
    @XmlEnumValue("Communications - Blogs")
    COMMUNICATIONS_BLOGS("Communications - Blogs"),
    @XmlEnumValue("Communications - Forums")
    COMMUNICATIONS_FORUMS("Communications - Forums"),
    @XmlEnumValue("Communications - Internet Relay Chat")
    COMMUNICATIONS_INTERNET_RELAY_CHAT("Communications - Internet Relay Chat"),
    @XmlEnumValue("Communications - Micro-Blogs")
    COMMUNICATIONS_MICRO_BLOGS("Communications - Micro-Blogs"),
    @XmlEnumValue("Communications - Mobile Communications")
    COMMUNICATIONS_MOBILE_COMMUNICATIONS("Communications - Mobile Communications"),
    @XmlEnumValue("Communications - Social Networks")
    COMMUNICATIONS_SOCIAL_NETWORKS("Communications - Social Networks"),
    @XmlEnumValue("Communications - User-Generated Content Websites")
    COMMUNICATIONS_USER_GENERATED_CONTENT_WEBSITES("Communications - User-Generated Content Websites"),
    @XmlEnumValue("Domain Registration")
    DOMAIN_REGISTRATION("Domain Registration"),
    @XmlEnumValue("Domain Registration - Dynamic DNS Services")
    DOMAIN_REGISTRATION_DYNAMIC_DNS_SERVICES("Domain Registration - Dynamic DNS Services"),
    @XmlEnumValue("Domain Registration - Legitimate Domain Registration Services")
    DOMAIN_REGISTRATION_LEGITIMATE_DOMAIN_REGISTRATION_SERVICES("Domain Registration - Legitimate Domain Registration Services"),
    @XmlEnumValue("Domain Registration - Malicious Domain Registrars")
    DOMAIN_REGISTRATION_MALICIOUS_DOMAIN_REGISTRARS("Domain Registration - Malicious Domain Registrars"),
    @XmlEnumValue("Domain Registration - Top-Level Domain Registrars")
    DOMAIN_REGISTRATION_TOP_LEVEL_DOMAIN_REGISTRARS("Domain Registration - Top-Level Domain Registrars"),
    @XmlEnumValue("Hosting")
    HOSTING("Hosting"),
    @XmlEnumValue("Hosting - Bulletproof / Rogue Hosting")
    HOSTING_BULLETPROOF_ROGUE_HOSTING("Hosting - Bulletproof / Rogue Hosting"),
    @XmlEnumValue("Hosting - Cloud Hosting")
    HOSTING_CLOUD_HOSTING("Hosting - Cloud Hosting"),
    @XmlEnumValue("Hosting - Compromised Server")
    HOSTING_COMPROMISED_SERVER("Hosting - Compromised Server"),
    @XmlEnumValue("Hosting - Fast Flux Botnet Hosting")
    HOSTING_FAST_FLUX_BOTNET_HOSTING("Hosting - Fast Flux Botnet Hosting"),
    @XmlEnumValue("Hosting - Legitimate Hosting")
    HOSTING_LEGITIMATE_HOSTING("Hosting - Legitimate Hosting"),
    @XmlEnumValue("Electronic Payment Methods")
    ELECTRONIC_PAYMENT_METHODS("Electronic Payment Methods");
    private final String value;

    AttackerInfrastructureTypeEnum10(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AttackerInfrastructureTypeEnum10 fromValue(String v) {
        for (AttackerInfrastructureTypeEnum10 c: AttackerInfrastructureTypeEnum10 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
