//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 01:41:27 PM EDT 
//


package org.mitre.stix.default_vocabularies_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MotivationEnum-1.1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MotivationEnum-1.1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Ideological"/>
 *     &lt;enumeration value="Ideological - Anti-Corruption"/>
 *     &lt;enumeration value="Ideological - Anti-Establishment"/>
 *     &lt;enumeration value="Ideological - Environmental"/>
 *     &lt;enumeration value="Ideological - Ethnic / Nationalist"/>
 *     &lt;enumeration value="Ideological - Information Freedom"/>
 *     &lt;enumeration value="Ideological - Religious"/>
 *     &lt;enumeration value="Ideological - Security Awareness"/>
 *     &lt;enumeration value="Ideological - Human Rights"/>
 *     &lt;enumeration value="Ego"/>
 *     &lt;enumeration value="Financial or Economic"/>
 *     &lt;enumeration value="Military"/>
 *     &lt;enumeration value="Opportunistic"/>
 *     &lt;enumeration value="Political"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MotivationEnum-1.1")
@XmlEnum
public enum MotivationEnum11 {

    @XmlEnumValue("Ideological")
    IDEOLOGICAL("Ideological"),
    @XmlEnumValue("Ideological - Anti-Corruption")
    IDEOLOGICAL_ANTI_CORRUPTION("Ideological - Anti-Corruption"),
    @XmlEnumValue("Ideological - Anti-Establishment")
    IDEOLOGICAL_ANTI_ESTABLISHMENT("Ideological - Anti-Establishment"),
    @XmlEnumValue("Ideological - Environmental")
    IDEOLOGICAL_ENVIRONMENTAL("Ideological - Environmental"),
    @XmlEnumValue("Ideological - Ethnic / Nationalist")
    IDEOLOGICAL_ETHNIC_NATIONALIST("Ideological - Ethnic / Nationalist"),
    @XmlEnumValue("Ideological - Information Freedom")
    IDEOLOGICAL_INFORMATION_FREEDOM("Ideological - Information Freedom"),
    @XmlEnumValue("Ideological - Religious")
    IDEOLOGICAL_RELIGIOUS("Ideological - Religious"),
    @XmlEnumValue("Ideological - Security Awareness")
    IDEOLOGICAL_SECURITY_AWARENESS("Ideological - Security Awareness"),
    @XmlEnumValue("Ideological - Human Rights")
    IDEOLOGICAL_HUMAN_RIGHTS("Ideological - Human Rights"),
    @XmlEnumValue("Ego")
    EGO("Ego"),
    @XmlEnumValue("Financial or Economic")
    FINANCIAL_OR_ECONOMIC("Financial or Economic"),
    @XmlEnumValue("Military")
    MILITARY("Military"),
    @XmlEnumValue("Opportunistic")
    OPPORTUNISTIC("Opportunistic"),
    @XmlEnumValue("Political")
    POLITICAL("Political");
    private final String value;

    MotivationEnum11(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MotivationEnum11 fromValue(String v) {
        for (MotivationEnum11 c: MotivationEnum11 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
